<a href="https://colab.research.google.com/github/mlaricobar/MITx-6.86x-machine-learning-with-python/blob/master/Assignments%20-%20Week%232.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [7]:
%cd /gdrive/'My Drive'/Capacitaciones/'[02] MIT Micromaster'/'[04] Machine Learning'/'[02] Week #2'

/gdrive/My Drive/Capacitaciones/[02] MIT Micromaster/[04] Machine Learning/[02] Week #2


In [9]:
!tar xvzf resources_project0.tar.gz

project0/
project0/debug.py
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
project0/debug.py’.bak’
project0/main.py
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
project0/main.py’.bak’
project0/test.py
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
project0/test.py’.bak’


In [11]:
!ls -l project0

total 9
-rw------- 1 root root  824 May  4 14:37 debug.py
-rw------- 1 root root  881 May  4 14:37 debug.py’.bak’
-rw------- 1 root root 1696 May  4 14:37 main.py
-rw------- 1 root root 2038 May  4 14:37 main.py’.bak’
-rw------- 1 root root 1446 May  4 14:37 test.py
-rw------- 1 root root 1446 May  4 14:37 test.py’.bak’


In [1]:
import numpy as np

In [4]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    return np.random.random([n,1])

In [5]:
randomization(4)

array([[0.64744255],
       [0.03649991],
       [0.1258    ],
       [0.97062468]])

In [7]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random([h, w])
    B = np.random.random([h, w])
    s = A + B
    return A, B, s


In [9]:
operations(1, 2)

(array([[0.85851553, 0.99201145]]),
 array([[0.71938424, 0.50222813]]),
 array([[1.57789977, 1.49423958]]))

In [13]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    return np.linalg.norm(A + B)


In [15]:
norm(np.random.random([1,5]), np.random.random([1,5]))

2.7522346965440208

In [ ]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    return np.tanh(np.matmul(weights.T, inputs))

In [ ]:
neural_network(np.random.random([2, 1]).T, np.random.random([2, 1]))